### ISSUE TITLE
Locking Tables

### ISSUE THREAD

**Issue by relu** [stas/pos#4]
Salut stas,

Locking tables funcționează puțin cam ciudat:
butoanele sunt disabled doar când dai click pe ele, ai putea să schimbi asta? Să apară dezactivate la vizualizarea meselor de un utilizator neautorizat. De asemenea, managerul trebuie să aibă și el dreptul de 'edita' mese...
Ai putea oare schimba icon-ul cu unul cu semnul 'interzis' pe mesele blocate, sau ceva de genul ăla?

Vin cu un rapor mai detaliat ceva mai târziu astăzi.

**Comment by stas** [comment]
În data de Jo, 09-06-2011 la 23:21 -0700, relu a scris:

> Locking tables funcționează puțin cam ciudat:
> butoanele sunt disabled doar când dai click pe ele, ai putea să
> schimbi asta? Să apară dezactivate la vizualizarea meselor de un
> utilizator neautorizat. De asemenea, managerul trebuie să aibă și el
> dreptul de 'edita' mese...

Editarea meselor se poate dacă adaugi „salesedit” la permisiuni, la fel
e și cu butonul minus...

> Ai putea oare schimba icon-ul cu unul cu semnul 'interzis' pe mesele
> blocate, sau ceva de genul ăla? 

O să mă uit, deși nu vreau să fac prea multe modificări. Eventual pot
adăuga un warning message.

**Comment by relu** [comment]
Warning? Bad idea! Ăia vor trebuii să mai dea click și pe OK/Cancel or whatever... problema nu e că nu se înțelege de ce e blocată masa, e că nu se știe din prima care sunt mesele blocate și care nu. Dacă vrei, ia ce am făcut eu în TPV-ul vechi, e funcțional și sunt doar vreo 10 linii de cod maxim.

Mai e o problemă cu table mergeing, când un chelner face merge cu o altă masă a altui chelner, el nu mai are access la masa respectivă și produsele sunt automat atribuite tichetului aparținând chelnerului care avea masa la care s-a făcut merge. Dar aici e filosofie mai mult... adevărul e că nu știm exact ce se întâmplă când două mese se unesc, cine preia comanda și cum.

**Comment by relu** [comment]
Am vorbit acum cu Jaco și e o problemă cu modul în care se face blocarea pe mese... avem nevoie ca masa să se blocheze doar dacă se introduce un produs, altfel nu. Se poate?

**Comment by stas** [comment]
Mă uit, deși nu mi se pare logic. Există cazuri în care un chelner trebuie să rezerve masa pentru o perioadă scurtă, și prin locking-ul actual poate face asta, dacă tre să adauge un produs, se complică treaba.

O să verific și locking-ul la tpv. Da vezi faceți o listă cu ce nu merge, sau zi-mi când ați gătat testing-ul, că nu pot sta fiecare 5 minute să verific câte un bug apoi să mă întorc la ale mele.

**Comment by relu** [comment]
E o problemă cu locking tables, mai exact cu permisiunile. Administratorul și managerul trebuie să aibă permisiuni pe orice masă chiar dacă e blocată de un chelner. În momentul de față doar utilizatorul care deschide masa are acces la masa respectivă.

**Comment by stas** [comment]
Vezi 3bc6ff38ce915727f6cfd498f1c74174eef40e2b
