### ISSUE TITLE
Kitchen Bar Printing

### ISSUE THREAD

**Issue by relu** [stas/pos#5]
Nu printeaza numele si cantitatea pe bonurile kitchen/bar, doar atributul (daca exista). Pentru a vedea, seteaza toate printerele pe screen. De asemenea, produsele cu atribute nu trebuie sa poata sa fie trimise la bar/bucatarie sau sa fie incheiata tranzactia daca nu au un atribut selectat.

**Comment by stas** [comment]
Despre ce atribute merge vorba?
Alea din meniul produsului?

**Comment by relu** [comment]
Ălea de sunt adăugate din Stock de acolo (Attributes).

**Comment by stas** [comment]
Eu nu am reușit să rezolv treaba cu atribute. Îmi poți descrie pas cu pas cum adaug un atribut și unde ar trebui să-l aleg?
