### ISSUE TITLE
Driver FPrint

### ISSUE THREAD

**Issue by relu** [stas/pos#6]
Nu uita sa adaugi driverul FPrint! Avem nevoie neaparat de el... am sa-ti trimit eu XML-ul cu noile date (cifrele alea) si setari sa le poti integra, sa ma anunti doar cand te apuci.

**Comment by stas** [comment]
Trimite pe mail xml-ul. O să mă uit.

**Comment by stas** [comment]
Relu, ai putea pune in loc de fisierul fprint al meu, asta
http://chopapp.com/#1pl8xxm9

Modifica si in DeviceTicket.java sa fie la fel linia de initializare ca la epson, si vezi daca merge imprimanta direct fara fprint.

**Comment by relu** [comment]
Trimite-mi te rog codul ăla undeva să-l pot lua raw, că acolo nu pot să-l copiez cum trebuie...

**Comment by stas** [comment]
http://paste.ubuntu.com/631722/
