### ISSUE TITLE
Factură

### ISSUE THREAD

**Issue by relu** [stas/pos#7]
Lipsește facutra, trebuie implementată, dar e ultimul lucru pe lista de prioritați

Prima e FPrint-ul vieții, apoi atributele la kitchen bar și rapoartele, apoi asta.

Ideea e că avem nevoie de o factură care să se printeze odată cu nota de plată, un checkbox sau un buton cum sunt cele existente. Dacă e selectat, se trimite la printat o factură cu datele firmelor luate de la company și clienți...

Nu mai avem timp, ăia ne trimit mâine lista cu produse :(

Dacă e ceva, sună-mă sau scrie-mi aici și vorbim.

**Comment by stas** [comment]
În data de Mi, 22-06-2011 la 11:28 -0700, relu a scris:

> Ideea e că avem nevoie de o factură care să se printeze odată cu nota
> de plată, un checkbox sau un buton cum sunt cele existente. Dacă e
> selectat, se trimite la printat o factură cu datele firmelor luate de
> la company și clienți...

Ai putea face o schiță cum ar trebui să arate factura (dacă poți, și în
paint e ok). Eu habar nu am ce date trebuie să conțină și unde să se
afle.

Mâine adaug restul detaliilor.
Fă și o listă de rapoarte de care o să fie nevoie.

**Comment by relu** [comment]
Modele de factură găsești multe pe net, alege pe care vrei, noi am găsit [asta](http://www.program-facturi.ro/media/images/factura.gif). Datele le iei de la customers...

Rapoartele le fac eu ca să nu te îngrămădesc pe tine. Doar să-mi dai un exemplu de query sql pe care pot să-l fac în funcție de apartenența unui produs la bar sau bucătărie...

**Comment by stas** [comment]
Hmm, Am adugat butoanele. Ma uit maine peste factura...
