### ISSUE TITLE
Компиляция в NetBeans?

### ISSUE THREAD

**Issue by ipadm** [stas/pos#9]
Привет тебе Стас! 

Делаешь ты великое дело, за что тебе огромное спасибо! Есть у меня вопрос: как настроить компиляцию твоего форка под NetBeans? Я к сожалению в Яве не силен. По инструкции как здесь http://code.google.com/p/openbravoposru/wiki/OpenbravoPOSruDeveloper не получилось. Пишет много ошибок как при открытии проекта так и при компиляции:

init:
deps-clean:
Created dir: /home/panda/NetBeansProjects/stas-pos-50b15e7/build
Updating property file: /home/panda/NetBeansProjects/stas-pos-50b15e7/build/built-clean.properties
Deleting directory /home/panda/NetBeansProjects/stas-pos-50b15e7/build
clean:
init:
deps-jar:
Created dir: /home/panda/NetBeansProjects/stas-pos-50b15e7/build
Updating property file: /home/panda/NetBeansProjects/stas-pos-50b15e7/build/built-jar.properties
Created dir: /home/panda/NetBeansProjects/stas-pos-50b15e7/build/classes
Created dir: /home/panda/NetBeansProjects/stas-pos-50b15e7/build/empty
Compiling 714 source files to /home/panda/NetBeansProjects/stas-pos-50b15e7/build/classes
/home/panda/NetBeansProjects/stas-pos-50b15e7/src-pos/com/openbravo/pos/ticket/CategoryInfo.java:33: duplicate class: com.openbravo.pos.ticket.CategoryInfo
public class CategoryInfo implements IKeyed {
/home/panda/NetBeansProjects/stas-pos-50b15e7/src-pos/com/openbravo/pos/ticket/ProductInfoExt.java:38: duplicate class: com.openbravo.pos.ticket.ProductInfoExt
public class ProductInfoExt implements Serializable {
/home/panda/NetBeansProjects/stas-pos-50b15e7/src-pos/com/openbravo/pos/ticket/TaxInfo.java:30: duplicate class: com.openbravo.pos.ticket.TaxInfo
public class TaxInfo implements Serializable, IKeyed {
/home/panda/NetBeansProjects/stas-pos-50b15e7/src-pos/com/openbravo/pos/ticket/TicketInfo.java:42: duplicate class: com.openbravo.pos.ticket.TicketInfo
public class TicketInfo implements SerializableRead, Externalizable {
/home/panda/NetBeansProjects/stas-pos-50b15e7/src-pos/com/openbravo/pos/ticket/TicketLineInfo.java:37: duplicate class: com.openbravo.pos.ticket.TicketLineInfo
public class TicketLineInfo implements SerializableWrite, SerializableRead, Serializable {
/home/panda/NetBeansProjects/stas-pos-50b15e7/src-pos/com/openbravo/pos/ticket/TicketTaxInfo.java:25: duplicate class: com.openbravo.pos.ticket.TicketTaxInfo
public class TicketTaxInfo {
/home/panda/NetBeansProjects/stas-pos-50b15e7/src-pos/com/openbravo/pos/ticket/UserInfo.java:27: duplicate class: com.openbravo.pos.ticket.UserInfo
public class UserInfo implements Serializable {
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:31: package javax.servlet does not exist
import javax.servlet.ServletContext;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:32: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:34: cannot find symbol
symbol  : class Bayeux
location: package org.cometd
import org.cometd.Bayeux;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:35: cannot find symbol
symbol  : class BayeuxListener
location: package org.cometd
import org.cometd.BayeuxListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:36: cannot find symbol
symbol  : class Channel
location: package org.cometd
import org.cometd.Channel;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:37: cannot find symbol
symbol  : class ChannelBayeuxListener
location: package org.cometd
import org.cometd.ChannelBayeuxListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:38: cannot find symbol
symbol  : class Client
location: package org.cometd
import org.cometd.Client;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:39: cannot find symbol
symbol  : class ClientBayeuxListener
location: package org.cometd
import org.cometd.ClientBayeuxListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:40: cannot find symbol
symbol  : class Extension
location: package org.cometd
import org.cometd.Extension;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:41: cannot find symbol
symbol  : class Message
location: package org.cometd
import org.cometd.Message;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:42: cannot find symbol
symbol  : class SecurityPolicy
location: package org.cometd
import org.cometd.SecurityPolicy;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:43: package org.mortbay.util.ajax does not exist
import org.mortbay.util.ajax.JSON;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:9: cannot find symbol
symbol  : class Bayeux
location: package org.cometd
import org.cometd.Bayeux;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:10: cannot find symbol
symbol  : class Message
location: package org.cometd
import org.cometd.Message;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:11: package org.mortbay.util does not exist
import org.mortbay.util.ArrayQueue;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:12: package org.mortbay.util does not exist
import org.mortbay.util.StringMap;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:13: package org.mortbay.util.ajax does not exist
import org.mortbay.util.ajax.JSON;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:52: cannot find symbol
symbol: class Bayeux
public abstract class AbstractBayeux extends MessagePool implements Bayeux
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:23: cannot find symbol
symbol  : class Channel
location: package org.cometd
import org.cometd.Channel;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:24: cannot find symbol
symbol  : class ChannelListener
location: package org.cometd
import org.cometd.ChannelListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:25: cannot find symbol
symbol  : class Client
location: package org.cometd
import org.cometd.Client;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:26: cannot find symbol
symbol  : class DataFilter
location: package org.cometd
import org.cometd.DataFilter;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:27: cannot find symbol
symbol  : class Message
location: package org.cometd
import org.cometd.Message;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:28: cannot find symbol
symbol  : class SubscriptionListener
location: package org.cometd
import org.cometd.SubscriptionListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:29: package org.mortbay.log does not exist
import org.mortbay.log.Log;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:30: package org.mortbay.util does not exist
import org.mortbay.util.LazyList;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ChannelImpl.java:39: cannot find symbol
symbol: class Channel
public class ChannelImpl implements Channel
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:22: cannot find symbol
symbol  : class Bayeux
location: package org.cometd
import org.cometd.Bayeux;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:23: cannot find symbol
symbol  : class Client
location: package org.cometd
import org.cometd.Client;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:24: cannot find symbol
symbol  : class DeliverListener
location: package org.cometd
import org.cometd.DeliverListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:25: cannot find symbol
symbol  : class Extension
location: package org.cometd
import org.cometd.Extension;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:26: cannot find symbol
symbol  : class ClientListener
location: package org.cometd
import org.cometd.ClientListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:27: cannot find symbol
symbol  : class Message
location: package org.cometd
import org.cometd.Message;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:28: cannot find symbol
symbol  : class MessageListener
location: package org.cometd
import org.cometd.MessageListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:29: cannot find symbol
symbol  : class QueueListener
location: package org.cometd
import org.cometd.QueueListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:30: cannot find symbol
symbol  : class RemoveListener
location: package org.cometd
import org.cometd.RemoveListener;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:31: package org.mortbay.util does not exist
import org.mortbay.util.ArrayQueue;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:32: package org.mortbay.util does not exist
import org.mortbay.util.LazyList;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:33: package org.mortbay.util.ajax does not exist
import org.mortbay.util.ajax.JSON;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/ClientImpl.java:42: cannot find symbol
symbol: class Client
public class ClientImpl implements Client
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:76: cannot find symbol
symbol  : class SecurityPolicy
location: class org.mortbay.cometd.AbstractBayeux
    protected SecurityPolicy _securityPolicy=new DefaultPolicy();
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:77: package JSON does not exist
    protected JSON.Literal _advice;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:78: package JSON does not exist
    protected JSON.Literal _multiFrameAdvice; 
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:92: cannot find symbol
symbol  : class HttpServletRequest
location: class org.mortbay.cometd.AbstractBayeux
    protected ThreadLocal<HttpServletRequest> _request = new ThreadLocal<HttpServletRequest>();
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:94: cannot find symbol
symbol  : class ServletContext
location: class org.mortbay.cometd.AbstractBayeux
    transient ServletContext _context;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:101: cannot find symbol
symbol  : class Extension
location: class org.mortbay.cometd.AbstractBayeux
    protected List<Extension> _extensions=new CopyOnWriteArrayList<Extension>();
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:102: package JSON does not exist
    protected JSON.Literal _transports=new JSON.Literal("[\""+Bayeux.TRANSPORT_LONG_POLL+ "\",\""+Bayeux.TRANSPORT_CALLBACK_POLL+"\"]");
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:103: cannot find symbol
symbol  : class ClientBayeuxListener
location: class org.mortbay.cometd.AbstractBayeux
    protected List<ClientBayeuxListener> _clientListeners=new CopyOnWriteArrayList<ClientBayeuxListener>();
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:104: cannot find symbol
symbol  : class ChannelBayeuxListener
location: class org.mortbay.cometd.AbstractBayeux
    protected List<ChannelBayeuxListener> _channelListeners=new CopyOnWriteArrayList<ChannelBayeuxListener>();
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:127: cannot find symbol
symbol  : class Extension
location: class org.mortbay.cometd.AbstractBayeux
    public void addExtension(Extension ext)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:133: cannot find symbol
symbol  : class Extension
location: class org.mortbay.cometd.AbstractBayeux
    public List<Extension> getExtensions()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:140: cannot find symbol
symbol  : class Extension
location: class org.mortbay.cometd.AbstractBayeux
    public void removeExtension(Extension ext)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:165: cannot find symbol
symbol  : class Channel
location: class org.mortbay.cometd.AbstractBayeux
    public Channel getChannel(String id, boolean create)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:200: cannot find symbol
symbol  : class Client
location: class org.mortbay.cometd.AbstractBayeux
    public Client getClient(String client_id)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:239: cannot find symbol
symbol  : class SecurityPolicy
location: class org.mortbay.cometd.AbstractBayeux
    public SecurityPolicy getSecurityPolicy()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/Transport.java:20: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletResponse;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/Transport.java:22: cannot find symbol
symbol  : class Message
location: package org.cometd
import org.cometd.Message;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:283: cannot find symbol
symbol  : class Message
location: class org.mortbay.cometd.AbstractBayeux
    public String handle(ClientImpl client, Transport transport, Message message) throws IOException
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:387: cannot find symbol
symbol  : class Client
location: class org.mortbay.cometd.AbstractBayeux
    public Client newClient(String idPrefix)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:445: cannot find symbol
symbol  : class Client
location: class org.mortbay.cometd.AbstractBayeux
    protected void doPublish(ChannelId to, Client from, Object data, String msgId)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:518: cannot find symbol
symbol  : class Client
location: class org.mortbay.cometd.AbstractBayeux
    public Client removeClient(String client_id)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:568: cannot find symbol
symbol  : class SecurityPolicy
location: class org.mortbay.cometd.AbstractBayeux
    public void setSecurityPolicy(SecurityPolicy securityPolicy)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:618: package JSON does not exist
    public void setAdvice(JSON.Literal advice)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:629: package JSON does not exist
    private Map<String,Object> multiFrameAdvice(JSON.Literal advice)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:646: package JSON does not exist
    public JSON.Literal getAdvice()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:673: cannot find symbol
symbol  : class HttpServletRequest
location: class org.mortbay.cometd.AbstractBayeux
    public HttpServletRequest getCurrentRequest()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:682: cannot find symbol
symbol  : class HttpServletRequest
location: class org.mortbay.cometd.AbstractBayeux
    void setCurrentRequest(HttpServletRequest request)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:690: cannot find symbol
symbol  : class Channel
location: class org.mortbay.cometd.AbstractBayeux
    public Collection<Channel> getChannels()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:707: cannot find symbol
symbol  : class Client
location: class org.mortbay.cometd.AbstractBayeux
    public Collection<Client> getClients()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:739: cannot find symbol
symbol  : class Channel
location: class org.mortbay.cometd.AbstractBayeux
    public Channel removeChannel(String channelId)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:754: cannot find symbol
symbol  : class ServletContext
location: class org.mortbay.cometd.AbstractBayeux
    protected void initialize(ServletContext context)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/AbstractBayeux.java:816: cannot find symbol
symbol  : class BayeuxListener
location: class org.mortbay.cometd.AbstractBayeux
    public void addListener(BayeuxListener listener)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:18: cannot find symbol
symbol  : class ArrayQueue
location: class org.mortbay.cometd.MessagePool
    final private ArrayQueue<MessageImpl> _messagePool;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessageImpl.java:11: cannot find symbol
symbol  : class Bayeux
location: package org.cometd
import org.cometd.Bayeux;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessageImpl.java:12: cannot find symbol
symbol  : class Message
location: package org.cometd
import org.cometd.Message;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessageImpl.java:13: package org.mortbay.util.ajax does not exist
import org.mortbay.util.ajax.JSON;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessageImpl.java:16: cannot find symbol
symbol: class Message
public class MessageImpl extends HashMap<String, Object> implements Message, org.mortbay.util.ajax.JSON.Generator
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessageImpl.java:16: package org.mortbay.util.ajax.JSON does not exist
public class MessageImpl extends HashMap<String, Object> implements Message, org.mortbay.util.ajax.JSON.Generator
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:19: cannot find symbol
symbol  : class ArrayQueue
location: class org.mortbay.cometd.MessagePool
    final private ArrayQueue<JSON.ReaderSource> _readerPool;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:19: package JSON does not exist
    final private ArrayQueue<JSON.ReaderSource> _readerPool;
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:38: cannot find symbol
symbol  : class JSON
location: class org.mortbay.cometd.MessagePool
    public JSON getJSON()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:47: cannot find symbol
symbol  : class JSON
location: class org.mortbay.cometd.MessagePool
    public void setJSON(JSON json)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:56: cannot find symbol
symbol  : class JSON
location: class org.mortbay.cometd.MessagePool
    public JSON getMsgJSON()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:65: cannot find symbol
symbol  : class JSON
location: class org.mortbay.cometd.MessagePool
    public void setMsgJSON(JSON msgJSON)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:74: cannot find symbol
symbol  : class JSON
location: class org.mortbay.cometd.MessagePool
    public JSON getBatchJSON()
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:83: cannot find symbol
symbol  : class JSON
location: class org.mortbay.cometd.MessagePool
    public void setBatchJSON(JSON batchJSON)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:100: cannot find symbol
symbol  : class Message
location: class org.mortbay.cometd.MessagePool
    public MessageImpl newMessage(Message associated)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:119: cannot find symbol
symbol  : class Message
location: class org.mortbay.cometd.MessagePool
    public Message[] parse(Reader reader) throws IOException
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:138: cannot find symbol
symbol  : class Message
location: class org.mortbay.cometd.MessagePool
    public Message[] parse(String s) throws IOException
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:149: cannot find symbol
symbol  : class Message
location: class org.mortbay.cometd.MessagePool
    public void parseTo(String fodder, List<Message> messages)
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:166: cannot find symbol
symbol  : class StringMap
location: class org.mortbay.cometd.MessagePool
    private StringMap _fieldStrings = new StringMap();
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:167: cannot find symbol
symbol  : class StringMap
location: class org.mortbay.cometd.MessagePool
    private StringMap _valueStrings = new StringMap();
/home/panda/NetBeansProjects/stas-pos-50b15e7/jetty/contrib/cometd/bayeux/src/main/java/org/mortbay/cometd/MessagePool.java:193: cannot find symbol
symbol  : class JSON
location: class org.mortbay.cometd.MessagePool
    private JSON _json = new JSON()
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
/home/panda/NetBeansProjects/stas-pos-50b15e7/nbproject/build-impl.xml:432: The following error occurred while executing this line:
/home/panda/NetBeansProjects/stas-pos-50b15e7/nbproject/build-impl.xml:222: Compile failed; see the compiler error output for details.
ПОСТРОЕНИЕ ЗАВЕРШЕНО НЕУДАЧНО (общее время: 29 секунд)

**Comment by stas** [comment]
Странно, 
не пробовал этот гайд?
http://wiki.openbravo.com/wiki/Projects/POS/Openbravo_POS_Developer_Guide#Edit_the_sources_using_the_Netbeans_IDE

Я им пользовался при сборке изначального кода.

**Comment by ipadm** [comment]
Спасибо за отзыв,

я собственно так и делал. А можешь выложить куда нибудь проект НетБинс
(сверни рабочую папку нетбинса) там правильно сформированный файлик
нетбинспроекта будет.

2011/7/24 stas reply@reply.github.com:

> Странно,
> не пробовал этот гайд?
> http://wiki.openbravo.com/wiki/Projects/POS/Openbravo_POS_Developer_Guide#Edit_the_sources_using_the_Netbeans_IDE
> 
> Я им пользовался при сборке изначального кода.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/stas/pos/issues/9#issuecomment-1640694

## 

Best regards,
Andrii Pertsiukh
http://discount-club.mobi

Please think of the environment before printing this email.

**Comment by stas** [comment]
Проекты в нетбинзе зависят от местоположение на диске, так-что я не думаю что это решит проблему.
Надо самому смотреть какие библиотеки не найдены, и куда те качать.
